.\" $Id: gwakeonlan.1 0.4 2020-05-04 00:53 muflone $
.\"
.\" Copyright (c) 2009-2024 Fabio Castelli

.TH GWAKEONLAN "1" "December 8, 2013"

.SH NAME
.B gWakeOnLAN
\- Wake up your machines using Wake on LAN

.SH SYNOPSIS
.B gwakeonlan
[options]

.SH DESCRIPTION
.PP
.B gWakeOnLAN
is a GTK+ utility to awaken turned off computers through the Wake on LAN feature.

.PP
The machines to turn on need to be shut off with the Wake on LAN magic packet
enabled. Linux environments can enable this using:

.PP
ethtool \-s <nic device> wol g

.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`\-').
A summary of options is included below.
.TP 
.B \-h, \-\-help
Show summary of options
.TP 
.B \-v, \-\-verbose
Show all error and information messages
.TP 
.B \-q, \-\-quiet
Hide all error and information messages

.SH FILES
Settings will be kept under ~/.config/gwakeonlan/

.SH REPORTING BUGS
Report bugs to https://github.com/muflone/gwakeonlan/issues/

.SH AUTHORS
.B gWakeOnLAN
was written by Fabio Castelli (Muflone) <muflone@muflone.com>

.SH HOMEPAGE
Home page: http://www.muflone.com/gwakeonlan/

Source code: https://github.com/muflone/gwakeonlan/

Translations: https://explore.transifex.com/muflone/gwakeonlan/

.SH COPYRIGHT
Copyright © 2009-2022 Fabio Castelli.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl-3.0.html>.

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
