version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can
  # use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool,
  # so you don't have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.9.5

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            # Dependencies for installation
            sudo apt-get install gettext
            # Dependencies for execution
            sudo apt-get install gir1.2-gtk-3.0 gobject-introspection libcairo2-dev libgirepository1.0-dev python3-gi

      - run:
          name: Install Python packages
          command: |
            python3 -m pip install --upgrade pip
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_ci.txt

      - run:
          name: Compile
          command: |
            python -m compileall gwakeonlan gwakeonlan.py setup.py

      - run:
          name: Lint with flake8
          command: |
            python -m flake8 gwakeonlan gwakeonlan.py setup.py
            python setup.py install --optimize=1 --root=build
            ls -laR .

      - run:
          name: Install
          command: |
            python setup.py install --optimize=1 --root=build
            ls -laR .

      - run:
          name: Show results
          command: |
            ls -laR .
